### ISSUE TITLE
关于xlsx

### ISSUE THREAD

**Issue by MathewChen** [captain-young/WYDocumentBrowser#1]
你好，关于Excel的xlsx格式我用了好几种方式预览都失败了。请问你预览xlsx格式的时候吗？谢谢指教

**Comment by captain-young** [comment]
我自己试了一下，用UIDocumentInteractionController方式是可以预览的，你看下是不是文件路径搞错了，导致预览失败

**Comment by MathewChen** [comment]
谢谢你的回复，原因就是我的路径出错，要手动添加到copy bundle resource才能生成路径。
